/* eslint-disable @typescript-eslint/naming-convention */
export const koreanTexts = {
  인터페이스: "Interface",
  메시지: "Message",
  통합조회: "Integrate Inquiry",
  작성자: "Writer/Author",
  전체: "All",
  인터페이스ID: "Interface ID",
  인터페이스ID명: "Interface ID name",
  온라인: "Online",
  저장완료: "Saved",
  결재진행중: "Payment in progress",
  등록완료: "Finished appointment",
  사용자관리: "User management",
  로그인이력: "Login history",
  사용자이름: "Username",
  사용자ID: "User ID",
  부서명: "Department",
  물리명: "Physical name",
  논리명: "Logical name",
  타입: "Type",
  길이: "Length",
  소수: "Decimal",
  기본값: "Default",
  설명: "Explanation",
  권한: "Role",
  잠금: "Lock",
  생성일: "Creation date",
  잠금해제: "Unlock",
  연락처: "Contact",
  사용자명: "Username",
  일반사용자: "Normal user",
  결재승인자: "Approval user",
  관리자: "Admin",
  이름: "Name",
  접속일시: "Connection date and time",
  기초정보관리: "Basic information management",
  공통헤더메시지관리: "Common header message management",
  공통헤더메시지명: "Common header message name",
  유형: "Category",
  대외기관명: "External organization name",
  사용여부: "Using or not",
  작성일: "Created date",
  사용: "Use",
  미사용: "Unused",
  메세지타입: "Message type",
  메시지타입확장정보관리: "Message type extended information management",
  정렬순서: "Sort order",
  반복타입: "Repeat type",
  반복횟수: "Number of repetitions",
  마스킹: "Masking",
  필드암호화: "Field encryption",
  메타체크: "Meta check",
  필수: "Essential",
  선택: "Select",
  필드명: "Field name",
  속성: "Property",
  확인하다: "Check",
  삭제: "Delete",
  공통코드명: "Common code name",
  공통코드관리: "Common code management",
  공통코드등록: "Common code registration",
  공통코드설명: "Common code description",
  공통헤더메시지상세: "Common header message details",
  메시지타입확장정보상세: "Message type extended information details",
  메시지타입: "Message type",
  확장정보코드명: "Extended information code name",
  확장정보표시명: "Extended information display name",
  메시지타입확장정보등록: "Register message type extension information",
  시스템코드관리: "System code management",
  아이디저장: "Save ID",
  올바른비밀번호를입력하세요: "Please enter the correct password",
  공통코드상세: "Common code details",
  공통코드편집: "Common code editing",
  등록이완료되었습니다: "Registration has been completed.",
  저장이완료되었습니다: "Save is complete.",
  삭제가완료되었습니다: "Deletion is complete.",
  "삭제하시겠습니까?": "Are you sure you want to delete?",
  공통코드세부정보: "Common code details",
  "올바른ID(또는사번,이름)를입력하세요":
    "Please enter the correct ID (or employee number or name).",
  체계명: "System name",
  비고: "Note",
  업무코드: "Business code",
  시스템관리: "System management",
  인터페이스ID설정: "Set interface ID",
  왼쪽부터: "From the left",
  오른쪽부터: "From the right",
  왼쪽채우기: "Fill left",
  오른쪽채우기: "Fill right",
  양식관리: "Template management",
  양식명: "Template name",
  파일명: "File name",
  배포서버명: "Distribution server name",
  배포서버코드: "Distribution server code",
  배포시스템관리: "Deployment System Management",
  연계서버: "Linked server",
  업무시스템: "Work system",
  유형상세: "Type details",
  확장정보관리: "Extended information management",
  확장정보등록: "Register extended information",
  타겟: "Target",
  소스: "Source",
  유형선택: "Select type",
  배포서버코드검색: "Deployment server code search",
  시스템코드를검색하면코드가입력됩니다:
    "Search for the system code and the code will be entered.",
  업무시스템등록: "Business system registration",
  시스템코드검색: "System code search",
  확장정보상세: "Extended information details",
  메시지명: "Message name",
  등록일시: "Registration date and time",
  양식상세: "Template details",
  템플릿양식명입력: "Enter template form name",
  첨부경로: "Attachment path",
  다운로드: "Download",
  메타: "Meta",
  표준항목조회: "Standard item search",
  승인일자: "Approval date",
  표준항목상세: "Standard item details",
  도메인물리명: "Domain physical name",
  도메인논리명: "domain logical name",
  도메인그룹: "Domain group",
  승인일시: "Approval date and time",
  담당자: "Manager",
  요청일시: "Request date and time",
  최초요청일시: "First request date and time",
  리소스타입: "Resource type",
  처리구분: "Processing classification",
  처리방식: "Processing method",
  리소스: "Resource",
  수정일시: "Date of modification",
  업무시스템체계설정: "Work system setup",
  코드: "Code",
  시스템코드: "System code",
  자리수: "Digit",
  문자열인덱스: "String index",
  빈자리채우기: "Fill empty space",
  빈자리값: "Empty place value",
  ID미리보기: "ID Preview",
  필드구분자: "Field separator",
  김신한: "Shinhan Kim",
  조회조건: "Search conditions",
  검색어3글자이상: "Search term 3 letters or more",
  업무시스템코드: "Business system code",
  입력방식: "Input method",
  필수여부: "Required",
  기본값입력: "Enter default value",
  표시조건: "Display conditions",
  숫자로입력: "Enter as a number",
  설명입력: "Enter description",
  실제파일명: "Actual file name",
  실제파일명입력: "Enter actual file name",
  양식등록: "Form registration",
  배포시스템관리등록: "Distribution system management registration",
  확장정보편집: "Edit extended information",
  문제가발생했습니다: "A problem has occurred.",
  사용자등록: "User registration",
  이필드는필수입니다: "This field is required",
  삭제하기: "Delete",
  사용자편집: "Edit user",
  사용자유형: "User type",
  비밀번호: "Password",
  비밀번호확인: "Verify password",
  이메일: "Email",
  휴대폰번호: "Phone number",
  회사명: "Company name",
  "부서명/직책": "Department name/position",
  잠금여부: "Lock status",
  사용자상세: "User details",
  사용자ID입력: "Enter user ID",
  "영문/숫자/특수문자조합8자리이상":
    "At least 8 characters of combination of English letters/numbers/special characters",
  사용자명입력: "Enter username",
  이메일형식으로입력: "Enter in email format",
  회사명입력: "Enter company name",
  부서명입력: "Enter department name",
  직책입력: "Enter position",
  업무시스템코드검색: "Business system code search",
  데이터를불러올수없습니다: "Data could not be loaded.",
  메타검색: "Meta search",
  메타검색결과: "Meta search results",
  계정정보: "Account Information",
  기본정보: "Basic Information",
  페이지당행: "Rows per page",
  이메일입력필드: "Email input field",
  한글은사용할수없습니다: "Korean is not available",
  비밀번호를동일하게입력하세요: "Please enter the same password",
  모든문자열이허용되지만비워둘수는없습니다:
    "Any string is allowed, but cannot be empty.",
  옵션리스트형식이올바르지않습니다: "The option list format is incorrect.",
  아이디를포함할수없습니다: "Cannot include ID",
  이름과동일하게사용할수없습니다: "Cannot be used with the same name",
  휴대폰번호를포함할수없습니다: "Cannot include mobile phone number",
  로그아웃되었습니다로그인화면으로이동합니다:
    "You have been logged out. Go to the login screen",
  "영문/숫자/특수문자조합8자이상으로입력해주세요":
    "Please enter at least 8 characters with a combination of English letters/numbers/special characters.",
  엑셀업로드: "Excel upload",
  양식을다운로드받고지정된양식내에서작성해주세요:
    "Please download the form and fill it out within the designated form.",
  업로드할파일선택: "Select file to upload",
  레벨: "Level",
  공통메시지명: "Common message name",
  메시지ID: "Message ID",
  공통메시지ID: "Common message ID",
  공통메시지조회: "Common message search",
  조회기간: "Viewing period",
  선택된메시지상세: "Selected message details",
  검색결과: "Search results",
  "설정값과동일한업무시스템,메시지타입을기준으로기본조회합니다":
    "Basic search is performed based on the same business system and message type as the settings.",
  공통헤더메시지ID: "Common header message ID",
  공통헤더메시지조회: "Common header message search",
  등록된공통헤더메시지전체를기준으로기본조회합니다:
    "Basic search is performed based on all registered common header messages.",
  적용하기: "Apply",
  선택된메타: "Selected meta",
  검색: "Search",
  추가: "Addition",
  메시지ID입력: "Enter message ID",
  공통메시지ID입력: "Enter common message ID",
  한글명입력: "Enter Korean name",
  총길이: "Total length",
  메시지길이의합이표시됩니다: "The sum of the message lengths is displayed.",
  버전정보: "Version information",
  공통메시지사용여부: "Whether to use common messages",
  상위메시지사용여부: "Whether or not to use the top message",
  메시지상세정보: "Message details",
  적용: "Apply",
  접속IP: "Connection IP",
  등록된배포경로: "Registered distribution path",
  등록된시스템코드: "Registered system code",
  배포서버선택: "Select deployment server",
  체계ID: "Scheme ID",
  동기: "Motivation",
  결재대기: "Waiting for payment",
  결재완료: "Payment completed",
  작성일자: "Date of issue",
  진행상태: "Progress",
  오류: "Error",
  버전: "Version",
  비동기: "Asynchronous",
  배포오류: "Deployment error",
  공통메시지: "Common message",
  상위메시지: "Top message",
  홈페이지: "Home page",
  파일찾기: "Find files",
  최종수정정보: "Last modified information",
  이전메시지조회: "View previous messages",
  상위메시지조회: "View top messages",
  공통헤더메시지: "Common header message",
  메시지상세: "Message details",
  메시지리뷰: "Message review",
  완료: "Complete",
  미완료: "Incomplete",
  메시지매핑: "Message Mapping",
  요청메시지: "Request message",
  응답메시지: "Response message",
  기안자: "Drafter",
  결재상신: "Payment Sangshin",
  상신내용작성: "Write your submission details",
  내용작성: "Write content",
  첨부파일: "Attachment",
  상신: "Sangsin",
  알림내역: "Notification history",
  공통코드ID: "Common code ID",
  공통코드검색: "Common code search",
  직접입력: "Direct input",
  공통코드검색결과: "Common code search results",
  공통코드직접입력: "Direct input of common code",
  공통코드명입력: "Enter common code name",
  결재자: "Approver",
  배포일지: "Distribution log",
  이력조회: "History search",
  배포이력: "Distribution history",
  버전이력: "Version history",
  오류상세: "Error details",
  업무시스템코드시스템상에서찾을수없음:
    "Business system code not found in system",
  결재완료되었습니다: "Payment has been completed",
  승인: "Approval",
  대기: "Atmosphere",
  미승인상태입니다: "It is in an unapproved state",
  상신내용: "Submission details",
  제목: "Title",
  내용: "Detail",
  결재내용: "Payment details",
  "승인/반려내용입력해주세요": "Please enter approval/rejection details",
  반려: "Companion",
  취소: "Cancellation",
  공통메시지관리: "Common message management",
  메시지등록: "Register message",
  인터페이스등록: "Interface Registration",
  사용자로그인이력: "User login history",
  사용자정보: "User information",
  아이디입력: "Enter ID",
  현재비밀번호: "Current Password",
  새비밀번호: "New password",
  비밀번호입력: "Enter Password",
  확인: "Check",
  양방향: "Two way",
  실시간: "Real time",
  교육임직원번호: "Education employee number",
  계리일자: "Actuarial date",
  물리명에러: "Physical name error",
  생성된리소스가없습니다: "No resources were created",
  새로운리소스를생성해보세요: "Try creating a new resource",
  인터페이스소스: "Interface source",
  인터페이스타겟: "Interface target",
  "매핑라인전체를초기화하시겠습니까?":
    "Are you sure you want to initialize the entire mapping line?",
  선택안함: "Not selected",
  코드명: "Code name",
  담보관리: "Collateral management",
  공통메시지상세: "Common message details",
  공통메시지등록: "Register common message",
  공통메시지편집: "Edit common messages",
  사용하지않음: "Not used",
  코드로검색시최소3자리이상입력하세요:
    "When searching by code, please enter at least 3 characters.",
  "시스템코드체계시스템 > 어플리케이션 > 모듈":
    "System code system: System > Application > Module",
  입력규칙메시지ID입력가이드따름: "Input rules: Follow message ID input guide",
  공통헤더메시지등록: "Register common header message",
  생성이완료되었습니다: "Creation is complete",
  새로운생성이완료되었습니다: "New creation is complete",
  업데이트가완료되었습니다: "Update has been completed",
  메시지확장정보: "Message expansion information",
  필드확장정보: "Field expansion information",
  생성완료: "Creation complete",
  공통코드ID입력: "Enter common code ID",
  코드상세정보: "Code Details",
  숫자입력: "Enter numbers",
  최대문자는100자입니다: "Maximum character limit is 100 characters",
  필수값입력후저장: "Enter required values and save",
  "소스/타겟 메시지까지 작성 후 등록":
    "Write and register source/target message",
  ID생성규칙: "ID creation rules",
  ID생성규칙정보: "About ID Generation Rules",
  등록정보: "Properties",
};
