/* eslint-disable @typescript-eslint/naming-convention */
export const koreanTexts = {
  인터페이스: "Interface",
  메시지: "Message",
  통합조회: "Integrate Inquiry",
  작성자: "Writer/Author",
  전체: "All",
  인터페이스ID: "Interface ID",
  인터페이스ID명: "Interface ID name",
  온라인: "Online",
  저장완료: "Saved",
  결재진행중: "Payment in progress",
  등록완료: "Finished appointment",
  "사용자 관리": "User management",
  "로그인 이력": "Login history",
  사용자이름: "Username",
  사용자ID: "User ID",
  부서명: "Department",
  물리명: "Physical name",
  논리명: "Logical name",
  타입: "Type",
  길이: "Length",
  소수: "Decimal",
  기본값: "Default",
  설명: "Explanation",
  권한: "Role",
  잠금: "Lock",
  생성일: "Creation date",
  잠금해제: "Unlock",
  연락처: "Contact",
  사용자명: "Username",
  일반사용자: "Normal user",
  결재승인자: "Approval user",
  관리자: "Admin",
  이름: "Name",
  접속일시: "Connection date and time",
  기초정보관리: "Basic information management",
  "공통헤더 메시지 관리": "Common header message management",
  공통헤더메시지명: "Common header message name",
  유형: "Category",
  "공통헤더 메시지명": "Common header message name",
  대외기관명: "External organization name",
  사용여부: "Using or not",
  작성일: "Created date",
  사용: "Use",
  미사용: "Unused",
  메세지타입: "Message type",
  "메시지 타입 확장정보 관리": "Message type extended information management",
  정렬순서: "Sort order",
  반복타입: "Repeat type",
  반복횟수: "Number of repetitions",
  마스킹: "Masking",
  필드암호화: "Field encryption",
  메타체크: "Meta check",
  필수: "Essential",
  선택: "Select",
  필드명: "Field name",
  속성: "Property",
  확인하다: "Check",
  삭제: "Delete",
  "공통코드 명": "Common code name",
  "기초정보 관리": "Basic information management",
  "공통코드 관리": "Common code management",
  "공통코드 등록": "Common code registration",
  "공통코드 설명": "Common code description",
  "공통 코드 관리": "Common code management",
  "공통헤더  메시지 상세": "Common header message details",
  "메시지 타입 확장정보 상세": "Message type extended information details",
  "메시지 타입": "Message type",
  "확장정보 코드명": "Extended information code name",
  "확장정보 표시명": "Extended information display name",
  공통코드명: "Common code name",
  "메시지 타입 확장정보 등록": "Register message type extension information",
  "시스템코드 관리": "System code management",
  "아이디 저장": "Save ID",
  "올바른 비밀번호를 입력하세요": "Please enter the correct password",
  "공통코드 상세": "Common code details",
  "공통코드 편집": "Common code editing",
  "등록이 완료되었습니다.": "Registration has been completed.",
  "저장이 완료되었습니다.": "Save is complete.",
  "삭제가 완료되었습니다.": "Deletion is complete.",
  "삭제하시겠습니까?": "Are you sure you want to delete?",
  "공통 코드 세부정보": "Common code details",
  "올바른 ID(또는 사번, 이름)를 입력하세요.":
    "Please enter the correct ID (or employee number or name).",
};
